global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend-replica1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-replica1:8081']

  - job_name: 'backend-replica2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-replica2:8081']